// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutpatientClinic.DataAccess.Context;

#nullable disable

namespace OutpatientClinic.DataAccess.Migrations
{
    [DbContext(typeof(OutpatientClinicDbContext))]
    [Migration("20250419202524_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "cc85a857-0008-4d5f-adfd-647de0a6d19f",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "95333524-c1ac-458b-9f9a-10d70237f1ea",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "f94138e6-b2f5-4fc0-a515-d3feb6680caa",
                            Name = "Receptionist",
                            NormalizedName = "RECEPTIONIST"
                        },
                        new
                        {
                            Id = "66c5da7a-30c5-44ac-a872-6f43d91864e9",
                            Name = "Nurse",
                            NormalizedName = "NURSE"
                        },
                        new
                        {
                            Id = "5c977cbd-03ae-47cf-9aa5-dbfc8f24975a",
                            Name = "Technical_Support",
                            NormalizedName = "TECHNICAL_SUPPORT"
                        },
                        new
                        {
                            Id = "5e1a1e4b-f86e-4141-a01b-0aa888ff371e",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        },
                        new
                        {
                            Id = "13045f24-6551-4562-9e48-4c51c41e0afb",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int")
                        .HasColumnName("ClinicID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__8ECDFCA2E6C3C030");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex(new[] { "AppointmentDateTime" }, "IX_Appointments_DateTime");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Billing", b =>
                {
                    b.Property<int>("BillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BillingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillingId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("InsuranceCoverage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("BillingId")
                        .HasName("PK__Billing__F1656D1317CDA8A3");

                    b.HasIndex(new[] { "AppointmentId" }, "IX_Billing_AppointmentID");

                    b.HasIndex(new[] { "PatientId" }, "IX_Billing_PatientID");

                    b.HasIndex(new[] { "PaymentStatus" }, "IX_Billing_PaymentStatus");

                    b.ToTable("Billing", (string)null);
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Clinic", b =>
                {
                    b.Property<int>("ClinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClinicID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ClinicId")
                        .HasName("PK__Clinics__3347C2FDCF7CE5D9");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.ContactInfo", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContactID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ContactId")
                        .HasName("PK__ContactI__5C6625BBA84CC8E1");

                    b.HasIndex(new[] { "Email" }, "UQ__ContactI__A9D105343C41FAFD")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("ContactInfo", (string)null);
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.DeliveryNote", b =>
                {
                    b.Property<int>("DeliveryNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DeliveryNoteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryNoteId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("int")
                        .HasColumnName("FacilityID");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<string>("ReceivedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("DeliveryNoteId")
                        .HasName("PK__Delivery__2A1CDD7E87E9E1FA");

                    b.HasIndex("FacilityId");

                    b.HasIndex(new[] { "OrderId" }, "IX_DeliveryNote_OrderID");

                    b.ToTable("DeliveryNote", (string)null);
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.DeliveryNoteDetail", b =>
                {
                    b.Property<int>("DeliveryDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DeliveryDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryDetailId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DeliveryNoteId")
                        .HasColumnType("int")
                        .HasColumnName("DeliveryNoteID");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    b.Property<int>("QuantityDelivered")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("DeliveryDetailId")
                        .HasName("PK__Delivery__EFD2C287E16C026E");

                    b.HasIndex("DeliveryNoteId");

                    b.HasIndex("ItemId");

                    b.ToTable("DeliveryNoteDetails");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BCD3678F47F");

                    b.HasIndex(new[] { "DepartmentName" }, "UQ__Departme__D949CC3420EBFA09")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DoctorId")
                        .HasName("PK__Doctors__2DC00EDFCF437B0A");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_Doctors_DepartmentID");

                    b.HasIndex(new[] { "LicenseNumber" }, "UQ__Doctors__E88901663FC5012E")
                        .IsUnique()
                        .HasFilter("[LicenseNumber] IS NOT NULL");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FacilityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<int?>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("ContactID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("FacilityId")
                        .HasName("PK__Facility__5FB08B94472946F9");

                    b.HasIndex("ContactId");

                    b.ToTable("Facility", (string)null);
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Insurance", b =>
                {
                    b.Property<int>("InsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InsuranceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("InsuranceId")
                        .HasName("PK__Insuranc__74231BC423DEEA1E");

                    b.HasIndex(new[] { "PatientId" }, "IX_Insurance_PatientID");

                    b.HasIndex(new[] { "PolicyNumber" }, "UQ__Insuranc__46DA01573CC12683")
                        .IsUnique();

                    b.ToTable("Insurance", (string)null);
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Inventory", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("int")
                        .HasColumnName("FacilityID");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("LastRestocked")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ItemId")
                        .HasName("PK__Inventor__727E83EB1BE9BB16");

                    b.HasIndex("FacilityId");

                    b.HasIndex(new[] { "ItemName" }, "IX_Inventory_ItemName");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.LabTest", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("Results")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("TestId")
                        .HasName("PK__LabTests__8CC33100C43F40D0");

                    b.HasIndex(new[] { "AppointmentId" }, "IX_LabTests_AppointmentID");

                    b.HasIndex(new[] { "PatientId" }, "IX_LabTests_PatientID");

                    b.ToTable("LabTests");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecordID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("RecordId")
                        .HasName("PK__MedicalR__FBDF78C9408CB1F9");

                    b.HasIndex(new[] { "AppointmentId" }, "UQ__MedicalR__8ECDFCA34135F362")
                        .IsUnique()
                        .HasFilter("[AppointmentID] IS NOT NULL");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultDosage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ForAdult")
                        .HasColumnType("bit");

                    b.Property<bool>("ForChildren")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MedicineId")
                        .HasName("PK__Medicines__1234567890ABCDEF");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            MedicineId = 1,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(4817),
                            DefaultDosage = "500mg",
                            Description = "For mild to moderate pain and fever",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Paracetamol",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 2,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(4869),
                            DefaultDosage = "400mg",
                            Description = "NSAID for pain/inflammation",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Ibuprofen",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 3,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(4874),
                            DefaultDosage = "81mg",
                            Description = "Pain relief and antiplatelet",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Aspirin",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 4,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(4877),
                            DefaultDosage = "220mg",
                            Description = "Long-lasting NSAID",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Naproxen",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 5,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(4881),
                            DefaultDosage = "50mg",
                            Description = "Opioid for moderate-severe pain",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Tramadol",
                            Type = "Capsule"
                        },
                        new
                        {
                            MedicineId = 6,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(4898),
                            DefaultDosage = "500mg",
                            Description = "Penicillin-type antibiotic",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Amoxicillin",
                            Type = "Capsule"
                        },
                        new
                        {
                            MedicineId = 7,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(4974),
                            DefaultDosage = "250mg",
                            Description = "Macrolide antibiotic",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Azithromycin",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 8,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(4980),
                            DefaultDosage = "500mg",
                            Description = "Fluoroquinolone antibiotic",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Ciprofloxacin",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 9,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(4983),
                            DefaultDosage = "100mg",
                            Description = "Tetracycline antibiotic",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Doxycycline",
                            Type = "Capsule"
                        },
                        new
                        {
                            MedicineId = 10,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(4987),
                            DefaultDosage = "400mg",
                            Description = "For anaerobic infections",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Metronidazole",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 11,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(4992),
                            DefaultDosage = "10mg",
                            Description = "Non-drowsy allergy relief",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Loratadine",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 12,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(4998),
                            DefaultDosage = "10mg",
                            Description = "24-hour allergy relief",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Cetirizine",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 13,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5002),
                            DefaultDosage = "180mg",
                            Description = "Non-sedating antihistamine",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Fexofenadine",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 14,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5005),
                            DefaultDosage = "25mg",
                            Description = "For allergies and sleep aid",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Diphenhydramine",
                            Type = "Capsule"
                        },
                        new
                        {
                            MedicineId = 15,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5009),
                            DefaultDosage = "4mg/5ml",
                            Description = "Liquid antihistamine",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Chlorpheniramine",
                            Type = "Syrup"
                        },
                        new
                        {
                            MedicineId = 16,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5026),
                            DefaultDosage = "20mg",
                            Description = "Proton pump inhibitor",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Omeprazole",
                            Type = "Capsule"
                        },
                        new
                        {
                            MedicineId = 17,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5030),
                            DefaultDosage = "150mg",
                            Description = "H2 blocker for heartburn",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Ranitidine",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 18,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5034),
                            DefaultDosage = "500mg",
                            Description = "Fast-acting antacid",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Calcium Carbonate",
                            Type = "Chewable"
                        },
                        new
                        {
                            MedicineId = 19,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5038),
                            DefaultDosage = "400mg/5ml",
                            Description = "Liquid antacid",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Magnesium Hydroxide",
                            Type = "Liquid"
                        },
                        new
                        {
                            MedicineId = 20,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5042),
                            DefaultDosage = "20mg",
                            Description = "Acid reducer",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Famotidine",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 21,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5045),
                            DefaultDosage = "50mg",
                            Description = "SSRI antidepressant",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Sertraline",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 22,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5050),
                            DefaultDosage = "20mg",
                            Description = "SSRI for depression/OCD",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Fluoxetine",
                            Type = "Capsule"
                        },
                        new
                        {
                            MedicineId = 23,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5053),
                            DefaultDosage = "75mg",
                            Description = "SNRI antidepressant",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Venlafaxine",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 24,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5057),
                            DefaultDosage = "150mg",
                            Description = "Atypical antidepressant",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Bupropion",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 25,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5060),
                            DefaultDosage = "10mg",
                            Description = "SSRI for anxiety/depression",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Escitalopram",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 26,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5064),
                            DefaultDosage = "500mg",
                            Description = "Type 2 diabetes management",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Metformin",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 27,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5068),
                            DefaultDosage = "100 units/ml",
                            Description = "Long-acting insulin",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Insulin Glargine",
                            Type = "Injection"
                        },
                        new
                        {
                            MedicineId = 28,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5071),
                            DefaultDosage = "80mg",
                            Description = "Sulfonylurea for diabetes",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Gliclazide",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 29,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5075),
                            DefaultDosage = "10mg",
                            Description = "SGLT2 inhibitor",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Empagliflozin",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 30,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5085),
                            DefaultDosage = "1.2mg",
                            Description = "GLP-1 receptor agonist",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Liraglutide",
                            Type = "Injection"
                        },
                        new
                        {
                            MedicineId = 31,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5120),
                            DefaultDosage = "100mcg/dose",
                            Description = "Relief of asthma symptoms",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Salbutamol",
                            Type = "Inhaler"
                        },
                        new
                        {
                            MedicineId = 32,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5124),
                            DefaultDosage = "0.5mg/ml",
                            Description = "For COPD",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Ipratropium",
                            Type = "Nebulizer"
                        },
                        new
                        {
                            MedicineId = 33,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5128),
                            DefaultDosage = "12mcg/dose",
                            Description = "Long-acting bronchodilator",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Formoterol",
                            Type = "Inhaler"
                        },
                        new
                        {
                            MedicineId = 34,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5133),
                            DefaultDosage = "200mg",
                            Description = "For chronic asthma",
                            ForAdult = true,
                            ForChildren = false,
                            IsDeleted = false,
                            Name = "Theophylline",
                            Type = "Tablet"
                        },
                        new
                        {
                            MedicineId = 35,
                            CreatedDate = new DateTime(2025, 4, 19, 22, 25, 20, 52, DateTimeKind.Local).AddTicks(5137),
                            DefaultDosage = "5mg",
                            Description = "Leukotriene receptor antagonist",
                            ForAdult = true,
                            ForChildren = true,
                            IsDeleted = false,
                            Name = "Montelukast",
                            Type = "Chewable"
                        });
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<int?>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("ContactID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PrimaryDoctorId")
                        .HasColumnType("int")
                        .HasColumnName("PrimaryDoctorID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId")
                        .HasName("PK__Patients__970EC34675504678");

                    b.HasIndex(new[] { "ContactId" }, "IX_Patients_ContactID");

                    b.HasIndex(new[] { "LastName", "FirstName" }, "IX_Patients_Name");

                    b.HasIndex(new[] { "PrimaryDoctorId" }, "IX_Patients_PrimaryDoctorID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MedicalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("RecordID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("PrescriptionId")
                        .HasName("PK__Prescrip__40130812F4CDA569");

                    b.HasIndex("MedicineId");

                    b.HasIndex("RecordId");

                    b.HasIndex(new[] { "MedicalName" }, "IX_Prescriptions_MedicalName");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<int?>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("ContactID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId")
                        .HasName("PK__Staff__96D4AAF719817DB0");

                    b.HasIndex(new[] { "ContactId" }, "IX_Staff_ContactID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("SupplierId")
                        .HasName("PK__Supplier__4BE66694F74E0005");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.SupplierOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("ExpectedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("int")
                        .HasColumnName("FacilityID");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("OrderId")
                        .HasName("PK__Supplier__C3905BAF90D0822A");

                    b.HasIndex("FacilityId");

                    b.HasIndex("SupplierId");

                    b.HasIndex(new[] { "Status" }, "IX_SupplierOrder_Status");

                    b.ToTable("SupplierOrder", (string)null);
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.SupplierOrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__Supplier__D3B9D30C62611F41");

                    b.HasIndex("ItemId");

                    b.HasIndex(new[] { "OrderId" }, "IX_SupplierOrderDetails_OrderID");

                    b.ToTable("SupplierOrderDetails");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OutpatientClinic.DataAccess.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Appointment", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.Clinic", "Clinic")
                        .WithMany("Appointments")
                        .HasForeignKey("ClinicId")
                        .IsRequired()
                        .HasConstraintName("FK__Appointme__Clini__4AB81AF0");

                    b.HasOne("OutpatientClinic.DataAccess.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Appointme__Depar__4BC73F29");

                    b.HasOne("OutpatientClinic.DataAccess.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK__Appointme__Docto__49C3F6B7");

                    b.HasOne("OutpatientClinic.DataAccess.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Appointme__Patie__48CFD27E");

                    b.Navigation("Clinic");

                    b.Navigation("Department");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Billing", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.Appointment", "Appointment")
                        .WithMany("Billings")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("FK__Billing__Appoint__17F790F9");

                    b.HasOne("OutpatientClinic.DataAccess.Entities.Patient", "Patient")
                        .WithMany("Billings")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK__Billing__Patient__17036CC0");

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.DeliveryNote", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.Facility", "Facility")
                        .WithMany("DeliveryNotes")
                        .HasForeignKey("FacilityId")
                        .HasConstraintName("FK__DeliveryN__Facil__7D439ABD");

                    b.HasOne("OutpatientClinic.DataAccess.Entities.SupplierOrder", "Order")
                        .WithMany("DeliveryNotes")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__DeliveryN__Order__7C4F7684");

                    b.Navigation("Facility");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.DeliveryNoteDetail", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.DeliveryNote", "DeliveryNote")
                        .WithMany("DeliveryNoteDetails")
                        .HasForeignKey("DeliveryNoteId")
                        .HasConstraintName("FK__DeliveryN__Deliv__02FC7413");

                    b.HasOne("OutpatientClinic.DataAccess.Entities.Inventory", "Item")
                        .WithMany("DeliveryNoteDetails")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK__DeliveryN__ItemI__03F0984C");

                    b.Navigation("DeliveryNote");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Doctor", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Doctors__Departm__3E52440B");

                    b.HasOne("OutpatientClinic.DataAccess.Entities.Staff", "DoctorNavigation")
                        .WithOne("Doctor")
                        .HasForeignKey("OutpatientClinic.DataAccess.Entities.Doctor", "DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Doctors__DoctorI__3D5E1FD2");

                    b.Navigation("Department");

                    b.Navigation("DoctorNavigation");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Facility", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.ContactInfo", "Contact")
                        .WithMany("Facilities")
                        .HasForeignKey("ContactId")
                        .HasConstraintName("FK__Facility__Contac__5DCAEF64");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Insurance", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.Patient", "Patient")
                        .WithMany("Insurances")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK__Insurance__Patie__114A936A");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Inventory", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.Facility", "Facility")
                        .WithMany("Inventories")
                        .HasForeignKey("FacilityId")
                        .HasConstraintName("FK__Inventory__Facil__6383C8BA");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.LabTest", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.Appointment", "Appointment")
                        .WithMany("LabTests")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("FK__LabTests__Appoin__0A9D95DB");

                    b.HasOne("OutpatientClinic.DataAccess.Entities.Patient", "Patient")
                        .WithMany("LabTests")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK__LabTests__Patien__09A971A2");

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.MedicalRecord", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.Appointment", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("OutpatientClinic.DataAccess.Entities.MedicalRecord", "AppointmentId")
                        .HasConstraintName("FK__MedicalRe__Appoi__52593CB8");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Patient", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.ContactInfo", "Contact")
                        .WithMany("Patients")
                        .HasForeignKey("ContactId")
                        .HasConstraintName("FK__Patients__Contac__4222D4EF");

                    b.HasOne("OutpatientClinic.DataAccess.Entities.Doctor", "PrimaryDoctor")
                        .WithMany("Patients")
                        .HasForeignKey("PrimaryDoctorId")
                        .HasConstraintName("FK__Patients__Primar__4316F928");

                    b.Navigation("Contact");

                    b.Navigation("PrimaryDoctor");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Prescription", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId");

                    b.HasOne("OutpatientClinic.DataAccess.Entities.MedicalRecord", "Record")
                        .WithMany("Prescriptions")
                        .HasForeignKey("RecordId")
                        .IsRequired()
                        .HasConstraintName("FK__Prescript__Recor__5812160E");

                    b.Navigation("Medicine");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Staff", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.ContactInfo", "Contact")
                        .WithMany("Staff")
                        .HasForeignKey("ContactId")
                        .HasConstraintName("FK__Staff__ContactID__36B12243");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.SupplierOrder", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.Facility", "Facility")
                        .WithMany("SupplierOrders")
                        .HasForeignKey("FacilityId")
                        .HasConstraintName("FK__SupplierO__Facil__6EF57B66");

                    b.HasOne("OutpatientClinic.DataAccess.Entities.Supplier", "Supplier")
                        .WithMany("SupplierOrders")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK__SupplierO__Suppl__6E01572D");

                    b.Navigation("Facility");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.SupplierOrderDetail", b =>
                {
                    b.HasOne("OutpatientClinic.DataAccess.Entities.Inventory", "Item")
                        .WithMany("SupplierOrderDetails")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK__SupplierO__ItemI__76969D2E");

                    b.HasOne("OutpatientClinic.DataAccess.Entities.SupplierOrder", "Order")
                        .WithMany("SupplierOrderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__SupplierO__Order__75A278F5");

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Appointment", b =>
                {
                    b.Navigation("Billings");

                    b.Navigation("LabTests");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Clinic", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.ContactInfo", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("Patients");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.DeliveryNote", b =>
                {
                    b.Navigation("DeliveryNoteDetails");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Facility", b =>
                {
                    b.Navigation("DeliveryNotes");

                    b.Navigation("Inventories");

                    b.Navigation("SupplierOrders");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Inventory", b =>
                {
                    b.Navigation("DeliveryNoteDetails");

                    b.Navigation("SupplierOrderDetails");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.MedicalRecord", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Billings");

                    b.Navigation("Insurances");

                    b.Navigation("LabTests");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Staff", b =>
                {
                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.Supplier", b =>
                {
                    b.Navigation("SupplierOrders");
                });

            modelBuilder.Entity("OutpatientClinic.DataAccess.Entities.SupplierOrder", b =>
                {
                    b.Navigation("DeliveryNotes");

                    b.Navigation("SupplierOrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
